// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	abi "github.com/ethereum/go-ethereum/accounts/abi"
	contracts "github.com/smartcontractkit/chainlink/core/services/eth/contracts"
	log "github.com/smartcontractkit/chainlink/core/services/log"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// Oracle is an autogenerated mock type for the Oracle type
type Oracle struct {
	mock.Mock
}

// ABI provides a mock function with given fields:
func (_m *Oracle) ABI() *abi.ABI {
	ret := _m.Called()

	var r0 *abi.ABI
	if rf, ok := ret.Get(0).(func() *abi.ABI); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*abi.ABI)
		}
	}

	return r0
}

// Call provides a mock function with given fields: result, methodName, args
func (_m *Oracle) Call(result interface{}, methodName string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, result, methodName)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, ...interface{}) error); ok {
		r0 = rf(result, methodName, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EncodeMessageCall provides a mock function with given fields: method, args
func (_m *Oracle) EncodeMessageCall(method string, args ...interface{}) ([]byte, error) {
	var _ca []interface{}
	_ca = append(_ca, method)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, ...interface{}) []byte); ok {
		r0 = rf(method, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(method, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMethodID provides a mock function with given fields: method
func (_m *Oracle) GetMethodID(method string) ([]byte, error) {
	ret := _m.Called(method)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeToLogs provides a mock function with given fields: listener
func (_m *Oracle) SubscribeToLogs(listener log.Listener) (bool, contracts.UnsubscribeFunc) {
	ret := _m.Called(listener)

	var r0 bool
	if rf, ok := ret.Get(0).(func(log.Listener) bool); ok {
		r0 = rf(listener)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 contracts.UnsubscribeFunc
	if rf, ok := ret.Get(1).(func(log.Listener) contracts.UnsubscribeFunc); ok {
		r1 = rf(listener)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(contracts.UnsubscribeFunc)
		}
	}

	return r0, r1
}

// UnpackLog provides a mock function with given fields: out, event, _a2
func (_m *Oracle) UnpackLog(out interface{}, event string, _a2 types.Log) error {
	ret := _m.Called(out, event, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, types.Log) error); ok {
		r0 = rf(out, event, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
